drop table if exists before_mierukas;
drop table if exists imtoks;
drop table if exists syains;

create table before_mierukas (
  id integer primary key,
  syain_code integer,
  jyoshi_point1 integer,
  jyoshi_point2 integer,
  jyoshi_point3 integer,
  jyoshi_point4 integer,
  jyoshi_point5 integer,
  jyoshi_point6 integer,
  jyoshi_point7 integer,
  jyoshi_point8 integer,
  jyoshi_point9 integer,
  jyoshi_point10 integer,
  jyoshi_point11 integer,
  jyoshi_point12 integer,
  jyoshi_point13 integer,
  jyoshi_point14 integer,
  jyoshi_point15 integer,
  jyoshi_point16 integer,
  jyoshi_point17 integer,
  jyoshi_point18 integer,
  jyoshi_point19 integer,
  jyoshi_point20 integer,
  jyoshi_point30 integer,
  jyoshi_point31 integer,
  jyoshi_point32 integer,
  jyoshi_point33 integer,
  jyoshi_point34 integer,
  jyoshi_point35 integer,
  jyoshi_point36 integer,
  jyoshi_point37 integer,
  jyoshi_point38 integer,
  jyoshi_point39 integer,
  jyoshi_point40 integer,
  jyoshi_point50 integer,
  jyoshi_point51 integer,
  jyoshi_point52 integer,
  jyoshi_point53 integer,
  jyoshi_point54 integer,
  jyoshi_point55 integer,
  jyoshi_point56 integer,
  jyoshi_point57 integer,
  jyoshi_point58 integer,
  jyoshi_point59 integer,
  jyoshi_point60 integer,
  jyoshi_point61 integer,
  jyoshi_point62 integer,
  jyoshi_point63 integer,
  jyoshi_point64 integer,
  jyoshi_point65 integer,
  jyoshi_point66 integer,
  jyoshi_point67 integer,
  jyoshi_point68 integer,
  jyoshi_point69 integer,
  jyoshi_point70 integer,
  kojin_point1 integer,
  kojin_point2 integer,
  kojin_point3 integer,
  kojin_point4 integer,
  kojin_point5 integer,
  kojin_point6 integer,
  kojin_point7 integer,
  kojin_point8 integer,
  kojin_point9 integer,
  kojin_point10 integer,
  kojin_point11 integer,
  kojin_point12 integer,
  kojin_point13 integer,
  kojin_point14 integer,
  kojin_point15 integer,
  kojin_point16 integer,
  kojin_point17 integer,
  kojin_point18 integer,
  kojin_point19 integer,
  kojin_point20 integer,
  kojin_point30 integer,
  kojin_point31 integer,
  kojin_point32 integer,
  kojin_point33 integer,
  kojin_point34 integer,
  kojin_point35 integer,
  kojin_point36 integer,
  kojin_point37 integer,
  kojin_point38 integer,
  kojin_point39 integer,
  kojin_point40 integer,
  kojin_point50 integer,
  kojin_point51 integer,
  kojin_point52 integer,
  kojin_point53 integer,
  kojin_point54 integer,
  kojin_point55 integer,
  kojin_point56 integer,
  kojin_point57 integer,
  kojin_point58 integer,
  kojin_point59 integer,
  kojin_point60 integer,
  kojin_point61 integer,
  kojin_point62 integer,
  kojin_point63 integer,
  kojin_point64 integer,
  kojin_point65 integer,
  kojin_point66 integer,
  kojin_point67 integer,
  kojin_point68 integer,
  kojin_point69 integer,
  kojin_point70 integer,
  created_at,
  updated_at
);

create table imtoks (
  id integer primary key,
  omise_code integer,
  omise_name string,
  created_at,
  updated_at
);

create table syains (
  id integer primary key,
  imtok_id integer,
  syain_code integer,
  syain_name string,
  yakusyoku string,
  created_at,
  updated_at
);

insert into imtoks(id,omise_code,omise_name) values (1,5002,"エビスタ西宮");
insert into imtoks(id,omise_code,omise_name) values (2,5006,"ららぽーと磐田");
insert into imtoks(id,omise_code,omise_name) values (3,5007,"イオン飯田");

insert into syains(id,imtok_id,syain_code,syain_name,yakusyoku) values (1,1,2278,"日名恵子","社員初級");
insert into syains(id,imtok_id,syain_code,syain_name,yakusyoku) values (2,1,1834,"今井聖子","アルバイト初級");
insert into syains(id,imtok_id,syain_code,syain_name,yakusyoku) values (3,1,2278,"日名恵子","社員初級");
