class CreateMierukas < ActiveRecord::Migration
  def change
    create_table :before_mierukas do |t|
      t.string :syain_code
      t.string :syain_name
      t.string :omise_code
      t.string :omise_name
      t.integer :jyun
      t.integer :nyusya_ymd
      t.string :yakusyoku
      t.integer :jyoshi_point1
      t.integer :jyoshi_point2
      t.integer :jyoshi_point3
      t.integer :jyoshi_point4
      t.integer :jyoshi_point5
      t.integer :jyoshi_point6
      t.integer :jyoshi_point7
      t.integer :jyoshi_point8
      t.integer :jyoshi_point9
      t.integer :jyoshi_point10
      t.integer :jyoshi_point11
      t.integer :jyoshi_point12
      t.integer :jyoshi_point13
      t.integer :jyoshi_point14
      t.integer :jyoshi_point15
      t.integer :jyoshi_point16
      t.integer :jyoshi_point17
      t.integer :jyoshi_point18
      t.integer :jyoshi_point19
      t.integer :jyoshi_point20
      t.integer :jyoshi_point30
      t.integer :jyoshi_point31
      t.integer :jyoshi_point32
      t.integer :jyoshi_point33
      t.integer :jyoshi_point34
      t.integer :jyoshi_point35
      t.integer :jyoshi_point36
      t.integer :jyoshi_point37
      t.integer :jyoshi_point38
      t.integer :jyoshi_point39
      t.integer :jyoshi_point40
      t.integer :jyoshi_point50
      t.integer :jyoshi_point51
      t.integer :jyoshi_point52
      t.integer :jyoshi_point53
      t.integer :jyoshi_point54
      t.integer :jyoshi_point55
      t.integer :jyoshi_point56
      t.integer :jyoshi_point57
      t.integer :jyoshi_point58
      t.integer :jyoshi_point59
      t.integer :jyoshi_point60
      t.integer :jyoshi_point61
      t.integer :jyoshi_point62
      t.integer :jyoshi_point63
      t.integer :jyoshi_point64
      t.integer :jyoshi_point65
      t.integer :jyoshi_point66
      t.integer :jyoshi_point67
      t.integer :jyoshi_point68
      t.integer :jyoshi_point69
      t.integer :jyoshi_point70
      t.integer :kojin_point1
      t.integer :kojin_point2
      t.integer :kojin_point3
      t.integer :kojin_point4
      t.integer :kojin_point5
      t.integer :kojin_point6
      t.integer :kojin_point7
      t.integer :kojin_point8
      t.integer :kojin_point9
      t.integer :kojin_point10
      t.integer :kojin_point11
      t.integer :kojin_point12
      t.integer :kojin_point13
      t.integer :kojin_point14
      t.integer :kojin_point15
      t.integer :kojin_point16
      t.integer :kojin_point17
      t.integer :kojin_point18
      t.integer :kojin_point19
      t.integer :kojin_point20
      t.integer :kojin_point30
      t.integer :kojin_point31
      t.integer :kojin_point32
      t.integer :kojin_point33
      t.integer :kojin_point34
      t.integer :kojin_point35
      t.integer :kojin_point36
      t.integer :kojin_point37
      t.integer :kojin_point38
      t.integer :kojin_point39
      t.integer :kojin_point40
      t.integer :kojin_point50
      t.integer :kojin_point51
      t.integer :kojin_point52
      t.integer :kojin_point53
      t.integer :kojin_point54
      t.integer :kojin_point55
      t.integer :kojin_point56
      t.integer :kojin_point57
      t.integer :kojin_point58
      t.integer :kojin_point59
      t.integer :kojin_point60
      t.integer :kojin_point61
      t.integer :kojin_point62
      t.integer :kojin_point63
      t.integer :kojin_point64
      t.integer :kojin_point65
      t.integer :kojin_point66
      t.integer :kojin_point67
      t.integer :kojin_point68
      t.integer :kojin_point69
      t.integer :kojin_point70
      t.timestamps
  end

  def change
    create_table :mierukas do |t|
      t.string :syain_code
      t.string :syain_name
      t.string :omise_code
      t.string :omise_name
      t.integer :jyun
      t.integer :nyusya_ymd
      t.string :yakusyoku
      t.integer :jyoshi_point1
      t.integer :jyoshi_point2
      t.integer :jyoshi_point3
      t.integer :jyoshi_point4
      t.integer :jyoshi_point5
      t.integer :jyoshi_point6
      t.integer :jyoshi_point7
      t.integer :jyoshi_point8
      t.integer :jyoshi_point9
      t.integer :jyoshi_point10
      t.integer :jyoshi_point11
      t.integer :jyoshi_point12
      t.integer :jyoshi_point13
      t.integer :jyoshi_point14
      t.integer :jyoshi_point15
      t.integer :jyoshi_point16
      t.integer :jyoshi_point17
      t.integer :jyoshi_point18
      t.integer :jyoshi_point19
      t.integer :jyoshi_point20
      t.integer :jyoshi_point30
      t.integer :jyoshi_point31
      t.integer :jyoshi_point32
      t.integer :jyoshi_point33
      t.integer :jyoshi_point34
      t.integer :jyoshi_point35
      t.integer :jyoshi_point36
      t.integer :jyoshi_point37
      t.integer :jyoshi_point38
      t.integer :jyoshi_point39
      t.integer :jyoshi_point40
      t.integer :jyoshi_point50
      t.integer :jyoshi_point51
      t.integer :jyoshi_point52
      t.integer :jyoshi_point53
      t.integer :jyoshi_point54
      t.integer :jyoshi_point55
      t.integer :jyoshi_point56
      t.integer :jyoshi_point57
      t.integer :jyoshi_point58
      t.integer :jyoshi_point59
      t.integer :jyoshi_point60
      t.integer :jyoshi_point61
      t.integer :jyoshi_point62
      t.integer :jyoshi_point63
      t.integer :jyoshi_point64
      t.integer :jyoshi_point65
      t.integer :jyoshi_point66
      t.integer :jyoshi_point67
      t.integer :jyoshi_point68
      t.integer :jyoshi_point69
      t.integer :jyoshi_point70
      t.integer :kojin_point1
      t.integer :kojin_point2
      t.integer :kojin_point3
      t.integer :kojin_point4
      t.integer :kojin_point5
      t.integer :kojin_point6
      t.integer :kojin_point7
      t.integer :kojin_point8
      t.integer :kojin_point9
      t.integer :kojin_point10
      t.integer :kojin_point11
      t.integer :kojin_point12
      t.integer :kojin_point13
      t.integer :kojin_point14
      t.integer :kojin_point15
      t.integer :kojin_point16
      t.integer :kojin_point17
      t.integer :kojin_point18
      t.integer :kojin_point19
      t.integer :kojin_point20
      t.integer :kojin_point30
      t.integer :kojin_point31
      t.integer :kojin_point32
      t.integer :kojin_point33
      t.integer :kojin_point34
      t.integer :kojin_point35
      t.integer :kojin_point36
      t.integer :kojin_point37
      t.integer :kojin_point38
      t.integer :kojin_point39
      t.integer :kojin_point40
      t.integer :kojin_point50
      t.integer :kojin_point51
      t.integer :kojin_point52
      t.integer :kojin_point53
      t.integer :kojin_point54
      t.integer :kojin_point55
      t.integer :kojin_point56
      t.integer :kojin_point57
      t.integer :kojin_point58
      t.integer :kojin_point59
      t.integer :kojin_point60
      t.integer :kojin_point61
      t.integer :kojin_point62
      t.integer :kojin_point63
      t.integer :kojin_point64
      t.integer :kojin_point65
      t.integer :kojin_point66
      t.integer :kojin_point67
      t.integer :kojin_point68
      t.integer :kojin_point69
      t.integer :kojin_point70
      t.timestamps
  end

end
